/****************************************************************
 Math.H
 BOOM : Bioinformatics Object Oriented Modules
 Copyright (C)2012 William H. Majoros (martiandna@gmail.com).
 This is OPEN SOURCE SOFTWARE governed by the Gnu General Public
 License (GPL) version 3, as described at www.opensource.org.
 ****************************************************************/
#ifndef INCL_Math_H
#define INCL_Math_H
#include <iostream>
#include "Constants.H"
#include "SumLogProbs.H"
using namespace std;
using namespace BOOM;

int ipow(int base,int exp); // integer power


#endif

